config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'welcome/index'
  get 'welcome/about', to: 'welcome#about', as: 'about'
  get 'welcome/dashboard', to: 'welcome#dashboard', as: 'dashboard'

  resources :tags

  resources :posts do
    resources :comments
  end

  resources :users

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :has_tags, dependent: :destroy
  has_many :posts, through: :has_tags
  accepts_nested_attributes_for :has_tags
  validates :name, presence: true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_admin!, except:[:index, :show]
  before_action :set_tag, except: [:index, :new, :create]
  breadcrumb 'Tags', :tags_path
  def index
    @tags = Tag.paginate(page: params[:page], per_page: 4)
  end

  def show
    breadcrumb @tag.name, tag_path(@tag)
    @posts = @tag.posts.paginate(page: params[:page], per_page: 10)
  end

  def new
    @tag = Tag.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to @tag
    else
      render :new
    end
  end

  def edit
    breadcrumb @tag.name, tag_path(@tag)
    breadcrumb 'Edit', edit_tag_path(@tag)
  end

  def update
    if @tag.update(tag_params)
      redirect_to @tag
    else
      render :edit 
    end
  end

  def destroy
    if @tag.destroy
      redirect_to tags_path
      flash[:success] = "Deleted succesfully."
    end
  end

  private

  def set_tag
    @tag ||= Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag)
      .permit(:name, :color, has_tags_attributes: [:id])
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_with(model: @tag, local: true) do |form| %>
  <%= render 'shared/errors', object: @tag %>

  <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control", placeholder: "Tag Name" %>
  </div>
  <div class="form-group">
      <%= form.label :color %>
      <%= form.color_field :color, class: "form-control" %>
  </div>
  <div class="actions">
    <%= form.submit "Send", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tags/_new.html.erb
<div class="modal-header">
  <h5 class="modal-title">New Tag</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<div class="modal-body">
  <%= render 'form' %>
</div>

app/views/tags/edit.html.erb
<%= render 'shared/breadcrumb' %>
<h1>Edit Tag</h1>

<%= render 'form' %>

app/views/tags/index.html.erb
<%= render 'shared/breadcrumb' %>
<h1>Listing Tags</h1>
<% if user_signed_in?   %>
<%=  link_to 'New tag', new_tag_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-tag'} if current_user.admin? %>
<% end %>
<div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
  <div class="card-deck">
    <% @tags.each do |tag| %>
      <div class="card">
        <div class="card-header" style="background-color: <%= tag.color %>;">
          <h5 class="card-title"><%= tag.name %></h5>
        </div>
        <div class="card-body">
        <%= link_to 'Show', tag_path(tag), class: "card-link"  %>
        <%= link_to 'Edit', edit_tag_path(tag), class: "card-link" %>
        <%= link_to 'Destroy', tag_path(tag),
        method: :delete,
        data: { confirm: 'Are you sure?' }, class: "card-link" %>
        </div>
      </div>
    <% end %>
  </div>
  <br>
<%= will_paginate @tags, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, next_label: '&raquo;', previous_label: '&laquo;', list_classes: %w(pagination justify-content-center) %>
<div id="modal-tag" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">	
    </div>
  </div>
</div>

app/views/tags/new.js.erb
$("#modal-tag").find(".modal-content").html("<%= j render 'new' %>");
$("#modal-tag").modal('show');

app/views/tags/show.html.erb
<%= render 'shared/breadcrumb' %>
<h3><%= @tag.name %></h3>

<% @posts.each do |post| %>
  <div class="jumbotron" style='background-color: <%= @tag.color %>;'>
    <h3> <%= post.title %> </h3>
    <p><%= sanitize post.description %></p>
    <%= link_to 'Eliminar', post, method: :delete, class: "btn btn-danger" %>
    <%= link_to "Leer Mas", post, class: "btn btn-primary" %>
  </div>
<%end%>

<%= will_paginate @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer, next_label: '&raquo;', previous_label: '&laquo;', list_classes: %w(pagination justify-content-center) %>

<%= link_to  "Back", tags_path %>