config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'welcome/index'
  get 'welcome/about', to: 'welcome#about', as: 'about'
  get 'welcome/dashboard', to: 'welcome#dashboard', as: 'dashboard'

  resources :tags

  resources :posts do
    resources :comments
  end

  resources :users

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-blog-material-blue">
    <%= link_to "Blog", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
        <span class="navbar-toggler-icon"></span>
      </button>

    <div class="navbar-collapse offcanvas-collapse" id="navbarMobile">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <li><%= link_to 'Posts', posts_path, class: 'nav-link' %></li>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Tags
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% Tag.all.each do |tag| %>
              <%= link_to tag.name, tag, class: 'dropdown-item' %>
            <%end%>  
            <div class="dropdown-divider"></div>
            <%=  link_to 'All Tags', tags_path, class: 'dropdown-item' %>
          </div>
       </li>    
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
      </ul> 

    <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">       
                  <img src="<%= current_user.image %>" class="profile-pic">
                  <%= current_user.name.split(" ")[0] if current_user.name.present? %>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <%= link_to(edit_user_registration_path, class: "dropdown-item") do %>
                    <%= fa_icon "cog 1x", text: "Edit Account" %>
                  <% end %>
                  <%= link_to(dashboard_path, class: "dropdown-item") do %>
                    <%= fa_icon "bars 1x", text: "Dashboard" %>
                  <% end %>
                  <div class="dropdown-divider"></div>
                  <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
                </div>
            </li>
        <% else %>         
            <li class="nav-item">
                <%= link_to "Login", new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to "Sign in", new_user_registration_path, class: 'nav-link' %>
            </li>
        <% end %>
     </ul>
     </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogTesting</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <br>
    <section class="container">
      <%= render partial: 'shared/flash', flash: flash %> 
      <%= yield %>
    </section>
  </body>
</html>